/*
 * Corda Testacles: Simple conveniences for your Corda Test Suites;
 * because who doesn't need to grow some more of those.
 *
 * Copyright (C) 2020 Manos Batsis
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 */
package com.github.manosbatsis.corda.testacles.mocknetwork.util

import java.util.Locale
import java.util.Random

data class Capital(val name: String, val countryCode: String)

object Capitals {
    val validCodes: Set<String> = setOf(*Locale.getISOCountries())

    var rand: Random = Random(System.currentTimeMillis())

    // Taken from http://techslides.com/list-of-countries-and-capitals
    // so probably outdated (2013), no offence intended!
    val list = listOf(
        Capital("King Edward Point", "GS"),
        Capital("Port-aux-Français", "TF"),
        Capital("Jerusalem", "PS"),
        Capital("Mariehamn", "AX"),
        Capital("Yaren", "NR"),
        Capital("Marigot", "MF"),
        Capital("Atafu", "TK"),
        Capital("El-Aaiún", "EH"),
        Capital("Kabul", "AF"),
        Capital("Tirana", "AL"),
        Capital("Algiers", "DZ"),
        Capital("Pago Pago", "AS"),
        Capital("Andorra la Vella", "AD"),
        Capital("Luanda", "AO"),
        Capital("The Valley", "AI"),
        Capital("Saint John's", "AG"),
        Capital("Buenos Aires", "AR"),
        Capital("Yerevan", "AM"),
        Capital("Oranjestad", "AW"),
        Capital("Canberra", "AU"),
        Capital("Vienna", "AT"),
        Capital("Baku", "AZ"),
        Capital("Nassau", "BS"),
        Capital("Manama", "BH"),
        Capital("Dhaka", "BD"),
        Capital("Bridgetown", "BB"),
        Capital("Minsk", "BY"),
        Capital("Brussels", "BE"),
        Capital("Belmopan", "BZ"),
        Capital("Porto-Novo", "BJ"),
        Capital("Hamilton", "BM"),
        Capital("Thimphu", "BT"),
        Capital("La Paz", "BO"),
        Capital("Sarajevo", "BA"),
        Capital("Gaborone", "BW"),
        Capital("Brasilia", "BR"),
        Capital("Road Town", "VG"),
        Capital("Bandar Seri Begawan", "BN"),
        Capital("Sofia", "BG"),
        Capital("Ouagadougou", "BF"),
        Capital("Rangoon", "MM"),
        Capital("Bujumbura", "BI"),
        Capital("Phnom Penh", "KH"),
        Capital("Yaounde", "CM"),
        Capital("Ottawa", "CA"),
        Capital("Praia", "CV"),
        Capital("George Town", "KY"),
        Capital("Bangui", "CF"),
        Capital("N'Djamena", "TD"),
        Capital("Santiago", "CL"),
        Capital("Beijing", "CN"),
        Capital("The Settlement", "CX"),
        Capital("West Island", "CC"),
        Capital("Bogota", "CO"),
        Capital("Moroni", "KM"),
        Capital("Kinshasa", "CD"),
        Capital("Brazzaville", "CG"),
        Capital("Avarua", "CK"),
        Capital("San Jose", "CR"),
        Capital("Yamoussoukro", "CI"),
        Capital("Zagreb", "HR"),
        Capital("Havana", "CU"),
        Capital("Willemstad", "CW"),
        Capital("Nicosia", "CY"),
        Capital("Prague", "CZ"),
        Capital("Copenhagen", "DK"),
        Capital("Djibouti", "DJ"),
        Capital("Roseau", "DM"),
        Capital("Santo Domingo", "DO"),
        Capital("Quito", "EC"),
        Capital("Cairo", "EG"),
        Capital("San Salvador", "SV"),
        Capital("Malabo", "GQ"),
        Capital("Asmara", "ER"),
        Capital("Tallinn", "EE"),
        Capital("Addis Ababa", "ET"),
        Capital("Stanley", "FK"),
        Capital("Torshavn", "FO"),
        Capital("Suva", "FJ"),
        Capital("Helsinki", "FI"),
        Capital("Paris", "FR"),
        Capital("Papeete", "PF"),
        Capital("Libreville", "GA"),
        Capital("Banjul", "GM"),
        Capital("Tbilisi", "GE"),
        Capital("Berlin", "DE"),
        Capital("Accra", "GH"),
        Capital("Gibraltar", "GI"),
        Capital("Athens", "GR"),
        Capital("Nuuk", "GL"),
        Capital("Saint George's", "GD"),
        Capital("Hagatna", "GU"),
        Capital("Guatemala City", "GT"),
        Capital("Saint Peter Port", "GG"),
        Capital("Conakry", "GN"),
        Capital("Bissau", "GW"),
        Capital("Georgetown", "GY"),
        Capital("Port-au-Prince", "HT"),
        Capital("Vatican City", "VA"),
        Capital("Tegucigalpa", "HN"),
        Capital("Budapest", "HU"),
        Capital("Reykjavik", "IS"),
        Capital("New Delhi", "IN"),
        Capital("Jakarta", "ID"),
        Capital("Tehran", "IR"),
        Capital("Baghdad", "IQ"),
        Capital("Dublin", "IE"),
        Capital("Douglas", "IM"),
        Capital("Jerusalem", "IL"),
        Capital("Rome", "IT"),
        Capital("Kingston", "JM"),
        Capital("Tokyo", "JP"),
        Capital("Saint Helier", "JE"),
        Capital("Amman", "JO"),
        Capital("Astana", "KZ"),
        Capital("Nairobi", "KE"),
        Capital("Tarawa", "KI"),
        Capital("Pyongyang", "KP"),
        Capital("Seoul", "KR"),
        Capital("Kuwait City", "KW"),
        Capital("Bishkek", "KG"),
        Capital("Vientiane", "LA"),
        Capital("Riga", "LV"),
        Capital("Beirut", "LB"),
        Capital("Maseru", "LS"),
        Capital("Monrovia", "LR"),
        Capital("Tripoli", "LY"),
        Capital("Vaduz", "LI"),
        Capital("Vilnius", "LT"),
        Capital("Luxembourg", "LU"),
        Capital("Skopje", "MK"),
        Capital("Antananarivo", "MG"),
        Capital("Lilongwe", "MW"),
        Capital("Kuala Lumpur", "MY"),
        Capital("Male", "MV"),
        Capital("Bamako", "ML"),
        Capital("Valletta", "MT"),
        Capital("Majuro", "MH"),
        Capital("Nouakchott", "MR"),
        Capital("Port Louis", "MU"),
        Capital("Mexico City", "MX"),
        Capital("Palikir", "FM"),
        Capital("Chisinau", "MD"),
        Capital("Monaco", "MC"),
        Capital("Ulaanbaatar", "MN"),
        Capital("Podgorica", "ME"),
        Capital("Plymouth", "MS"),
        Capital("Rabat", "MA"),
        Capital("Maputo", "MZ"),
        Capital("Windhoek", "NA"),
        Capital("Kathmandu", "NP"),
        Capital("Amsterdam", "NL"),
        Capital("Noumea", "NC"),
        Capital("Wellington", "NZ"),
        Capital("Managua", "NI"),
        Capital("Niamey", "NE"),
        Capital("Abuja", "NG"),
        Capital("Alofi", "NU"),
        Capital("Kingston", "NF"),
        Capital("Saipan", "MP"),
        Capital("Oslo", "NO"),
        Capital("Muscat", "OM"),
        Capital("Islamabad", "PK"),
        Capital("Melekeok", "PW"),
        Capital("Panama City", "PA"),
        Capital("Port Moresby", "PG"),
        Capital("Asuncion", "PY"),
        Capital("Lima", "PE"),
        Capital("Manila", "PH"),
        Capital("Adamstown", "PN"),
        Capital("Warsaw", "PL"),
        Capital("Lisbon", "PT"),
        Capital("San Juan", "PR"),
        Capital("Doha", "QA"),
        Capital("Bucharest", "RO"),
        Capital("Moscow", "RU"),
        Capital("Kigali", "RW"),
        Capital("Gustavia", "BL"),
        Capital("Jamestown", "SH"),
        Capital("Basseterre", "KN"),
        Capital("Castries", "LC"),
        Capital("Saint-Pierre", "PM"),
        Capital("Kingstown", "VC"),
        Capital("Apia", "WS"),
        Capital("San Marino", "SM"),
        Capital("Sao Tome", "ST"),
        Capital("Riyadh", "SA"),
        Capital("Dakar", "SN"),
        Capital("Belgrade", "RS"),
        Capital("Victoria", "SC"),
        Capital("Freetown", "SL"),
        Capital("Singapore", "SG"),
        Capital("Philipsburg", "SX"),
        Capital("Bratislava", "SK"),
        Capital("Ljubljana", "SI"),
        Capital("Honiara", "SB"),
        Capital("Mogadishu", "SO"),
        Capital("Pretoria", "ZA"),
        Capital("Juba", "SS"),
        Capital("Madrid", "ES"),
        Capital("Colombo", "LK"),
        Capital("Khartoum", "SD"),
        Capital("Paramaribo", "SR"),
        Capital("Longyearbyen", "SJ"),
        Capital("Mbabane", "SZ"),
        Capital("Stockholm", "SE"),
        Capital("Bern", "CH"),
        Capital("Damascus", "SY"),
        Capital("Taipei", "TW"),
        Capital("Dushanbe", "TJ"),
        Capital("Dar es Salaam", "TZ"),
        Capital("Bangkok", "TH"),
        Capital("Dili", "TL"),
        Capital("Lome", "TG"),
        Capital("Nuku'alofa", "TO"),
        Capital("Port of Spain", "TT"),
        Capital("Tunis", "TN"),
        Capital("Ankara", "TR"),
        Capital("Ashgabat", "TM"),
        Capital("Grand Turk", "TC"),
        Capital("Funafuti", "TV"),
        Capital("Kampala", "UG"),
        Capital("Kyiv", "UA"),
        Capital("Abu Dhabi", "AE"),
        Capital("London", "GB"),
        Capital("Montevideo", "UY"),
        Capital("Tashkent", "UZ"),
        Capital("Port-Vila", "VU"),
        Capital("Caracas", "VE"),
        Capital("Hanoi", "VN"),
        Capital("Charlotte Amalie", "VI"),
        Capital("Mata-Utu", "WF"),
        Capital("Sanaa", "YE"),
        Capital("Lusaka", "ZM"),
        Capital("Harare", "ZW"),
        Capital("Diego Garcia", "IO")
    )

    fun randomCapital(): Capital {
        val capital = list[rand.nextInt(list.size)]
        return if(validCodes.contains(capital.countryCode)) capital else randomCapital()
    }
}