package com.github.manosbatsis.corda.testacles.mocknetwork.util

import java.util.Random

data class Capital(val name: String, val countryCode: String)

object Capitals {
    var rand: Random = Random(System.currentTimeMillis())
    // Taken from https://geographyfieldwork.com/WorldCapitalCities.htm
    val list = listOf(
            Capital("Abu Dhabi", "United Arab Emirates"),
            Capital("Abuja", "Nigeria"),
            Capital("Acra", "Ghana"),
            Capital("Addis Acbaba", "Ethiopia"),
            Capital("Algiers", "Algeria"),
            Capital("Amman", "Jordan"),
            Capital("Amsterdam", "Netherlands"),
            Capital("Andorra la Vella", "Andorra"),
            Capital("Ankara", "Turkey"),
            Capital("Antananarivo", "Madagascar"),
            Capital("Apia", "Samoa"),
            Capital("Ashgabat", "Turkmenistan"),
            Capital("Asmara", "Eritrea"),
            Capital("Asuncion", "Paraguay"),
            Capital("Athens", "Greece"),
            Capital("Baghdad", "Iraq"),
            Capital("Baku", "Azerbaijan"),
            Capital("Bamako", "Mali"),
            Capital("Bandar Seri Begawan", "Brunei"),
            Capital("Bangkok", "Thailand"),
            Capital("Bangui", "Central African Republic"),
            Capital("Banjul", "Gambia"),
            Capital("Basseterre", "Saint Kitts and Nevis"),
            Capital("Beijing", "China"),
            Capital("Beirut", "Lebanon"),
            Capital("Belfast", "Northern Ireland"),
            Capital("Belgrade", "Serbia"),
            Capital("Belmopan", "Belize"),
            Capital("Berlin", "Germany"),
            Capital("Bern", "Switzerland"),
            Capital("Bishkek", "Kyrgyzstan"),
            Capital("Bissau", "Guinea-Bissau"),
            Capital("Bogota", "Colombia"),
            Capital("Brasilia", "Brazil"),
            Capital("Bratislava", "Slovakia"),
            Capital("Brazzaville", "Congo, Republic of the"),
            Capital("Bridgetown", "Barbados"),
            Capital("Brussels", "Belgium"),
            Capital("Bucharest", "Romania"),
            Capital("Budapest", "Hungary"),
            Capital("Buenos Aires", "Argentina"),
            Capital("Cairo", "Egypt"),
            Capital("Canberra", "Australia"),
            Capital("Caracas", "Venezuela"),
            Capital("Cardiff", "Wales"),
            Capital("Castries", "Saint Lucia"),
            Capital("Chisinau", "Moldova"),
            Capital("Colombo", "Sri Lanka"),
            Capital("Conakry", "Guinea"),
            Capital("Copenhagen", "Denmark"),
            Capital("Dakar", "Senegal"),
            Capital("Damascus", "Syria"),
            Capital("Dhaka", "Bangladesh"),
            Capital("Dili", "East Timor"),
            Capital("Djibouti", "Djibouti"),
            Capital("Dodoma", "Tanzania"),
            Capital("Doha", "Qatar"),
            Capital("Dublin", "Ireland"),
            Capital("Dushanbe", "Tajikistan"),
            Capital("Edinburgh", "Scotland"),
            Capital("Freetown", "Sierra Leone"),
            Capital("Funafuti", "Tuvalu"),
            Capital("Gaborone", "Botswana"),
            Capital("Georgetown", "Guyana"),
            Capital("Gitega", "Burundi"),
            Capital("Guatemala City", "Guatemala"),
            Capital("Hanoi", "Vietnam"),
            Capital("Harare", "Zimbabwe"),
            Capital("Havana", "Cuba"),
            Capital("Helsinki", "Finland"),
            Capital("Honiara", "Solomon Islands"),
            Capital("Islamabad", "Pakistan"),
            Capital("Jakarta", "Indonesia"),
            Capital("Jerusalem", "Israel"),
            Capital("Juba", "South Sudan"),
            Capital("Kabul", "Afghanistan"),
            Capital("Kampala", "Uganda"),
            Capital("Kathmandu", "Nepal"),
            Capital("Khartoum", "Sudan"),
            Capital("Kiev", "Ukraine"),
            Capital("Kigali", "Rwanda"),
            Capital("Kingston", "Jamaica"),
            Capital("Kingstown", "Saint Vincent and the Grenadines"),
            Capital("Kinshasa", "Congo, Democratic Republic of the"),
            Capital("Kuala Lumpur", "Malaysia"),
            Capital("Kuwait City", "Kuwait"),
            Capital("Sucre", "Bolivia"),
            Capital("Libreville", "Gabon"),
            Capital("Lilongwe", "Malawi"),
            Capital("Lima", "Peru"),
            Capital("Lisbon", "Portugal"),
            Capital("Ljubljana", "Slovenia"),
            Capital("Lome", "Togo"),
            Capital("London", "England"),
            Capital("London", "United Kingdom"),
            Capital("Luanda", "Angola"),
            Capital("Lusaka", "Zambia"),
            Capital("Luxembourg", "Luxembourg"),
            Capital("Madrid", "Spain"),
            Capital("Majuro", "Marshall Islands"),
            Capital("Malabo", "Equatorial Guinea"),
            Capital("Male", "Maldives"),
            Capital("Managua", "Nicaragua"),
            Capital("Manama", "Bahrain"),
            Capital("Manila", "Philippines"),
            Capital("Maputo", "Mozambique"),
            Capital("Maseru", "Lesotho"),
            Capital("Mbabana", "Eswatini (Swaziland)"),
            Capital("Melekeok", "Palau"),
            Capital("Mexico City", "Mexico"),
            Capital("Minsk", "Belarus"),
            Capital("Mogadishu", "Somalia"),
            Capital("Monaco", "Monaco"),
            Capital("Monrovia", "Liberia"),
            Capital("Montevideo", "Uruguay"),
            Capital("Moroni", "Comoros"),
            Capital("Moscow", "Russia"),
            Capital("Muscat", "Oman"),
            Capital("N'Djamena", "Chad"),
            Capital("Nairobi", "Kenya"),
            Capital("Nassau", "Bahamas"),
            Capital("Nay Pyi Taw", "Myanmar (Burma)"),
            Capital("New Delhi", "India"),
            Capital("Niamey", "Niger"),
            Capital("Nicosia", "Cyprus"),
            Capital("No official capital", "Nauru"),
            Capital("Nouakchott", "Mauritania"),
            Capital("Nuku'alofa", "Tonga"),
            Capital("Nur-Sultan", "Kazakhstan"),
            Capital("Oslo", "Norway"),
            Capital("Ottawa", "Canada"),
            Capital("Ouagadougou", "Burkina Faso"),
            Capital("Palikir", "Federated States of Micronesia"),
            Capital("Panama City", "Panama"),
            Capital("Paramaribo", "Suriname"),
            Capital("Paris", "France"),
            Capital("Phnom Penh", "Cambodia"),
            Capital("Podgorica", "Montenegro"),
            Capital("Port au Prince", "Haiti"),
            Capital("Port Louis", "Mauritius"),
            Capital("Port Moresby", "Papua New Guinea"),
            Capital("Port of Spain", "Trinidad and Tobago"),
            Capital("Port Vila", "Vanuatu"),
            Capital("Porto Novo", "Benin"),
            Capital("Prague", "Czech Republic (Czechia)"),
            Capital("Praia", "Cape Verde"),
            Capital("Pretoria, Bloemfontein, Cape Town", "South Africa"),
            Capital("Pristina", "Kosovo"),
            Capital("Pyongyang", "North Korea"),
            Capital("Quito", "Ecuador"),
            Capital("Rabat", "Morocco"),
            Capital("Reykjavik", "Iceland"),
            Capital("Riga", "Latvia"),
            Capital("Riyadh", "Saudi Arabia"),
            Capital("Rome", "Italy"),
            Capital("Roseau", "Dominica"),
            Capital("Saint George's", "Grenada"),
            Capital("Saint John's", "Antigua and Barbuda"),
            Capital("San Jose", "Costa Rica"),
            Capital("San Marino", "San Marino"),
            Capital("San Salvador", "El Salvador"),
            Capital("Sana'a", "Yemen"),
            Capital("Santiago", "Chile"),
            Capital("Santo Domingo", "Dominican Republic"),
            Capital("Sao Tome", "Sao Tome and Principe"),
            Capital("Sarajevo", "Bosnia and Herzegovina"),
            Capital("Seoul", "South Korea"),
            Capital("Singapore", "Singapore"),
            Capital("Skopje", "North Macedonia (Macedonia)"),
            Capital("Sofia", "Bulgaria"),
            Capital("Stockholm", "Sweden"),
            Capital("Suva", "Fiji"),
            Capital("Taipei", "Taiwan"),
            Capital("Tallinn", "Estonia"),
            Capital("Tarawa Atoll", "Kiribati"),
            Capital("Tashkent", "Uzbekistan"),
            Capital("Tbilisi", "Georgia"),
            Capital("Tegucigalpa", "Honduras"),
            Capital("Tehran", "Iran"),
            Capital("Thimphu", "Bhutan"),
            Capital("Tirana (Tirane)", "Albania"),
            Capital("Tokyo", "Japan"),
            Capital("Tripoli", "Libya"),
            Capital("Tunis", "Tunisia"),
            Capital("Ulaanbaatar", "Mongolia"),
            Capital("Vaduz", "Liechtenstein"),
            Capital("Valletta", "Malta"),
            Capital("Vatican City", "Vatican City"),
            Capital("Victoria", "Seychelles"),
            Capital("Vienna", "Austria"),
            Capital("Vientiane", "Laos"),
            Capital("Vilnius", "Lithuania"),
            Capital("Warsaw", "Poland"),
            Capital("Washington D.C.", "United States"),
            Capital("Wellington", "New Zealand"),
            Capital("Windhoek", "Namibia"),
            Capital("Yamoussoukro", "Côte d'Ivoire (Ivory Coast)"),
            Capital("Yaounde", "Cameroon"),
            Capital("Yerevan", "Armenia"),
            Capital("Zagreb", "Croatia")
    )
    fun randomCapital(): Capital = list[rand.nextInt(list.size)]
}