# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    resource_class: large

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Run tests!
      - run: ./gradlew build -x dokkaJavadoc

      # Store test reports
      - store_artifacts:
          path: corda-testacles-cordapp-example/build/reports

      # Store generated nodes
      - run:
          name: Compress nodes generated by Corda Testacles
          command: tar -cvzf testacles.tar corda-testacles-cordapp-example/build/testacles
      - store_artifacts:
          path: testacles.tar
          destination: testacles

