# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    resource_class: large

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Run tests!
      - run: ./gradlew mocknetworkTest -x test -x dokkaJavadoc
      - run: ./gradlew nodedriverTest -x test -x dokkaJavadoc
      - run: ./gradlew cordformTest -x test -x dokkaJavadoc
      # Store test results
      - store_test_results:
          path: corda-testacles-cordapp-example/build/test-results

      # Store test reports
      #- store_artifacts:
      #    path: corda-testacles-cordapp-example/build/reports
      #    destination: testreport
      # Store generated nodes
      - store_artifacts:
          path: corda-testacles-cordapp-example/build/testacles
          destination: testacles

