# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  circleci: leoilab/circleci@1.0.0
machine: true
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    resource_class: large

    working_directory: ~/repo

    environment:
      #JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - circleci/use-openjdk8
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
#      - run:
#          name: Install OpenJDK 8
#          command: |
#            sudo apt-get update && sudo apt-get install openjdk-8-jdk
#            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
#            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
#            java -version
      - run: java -version
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Run tests!
      - run: ./gradlew clean build -x dokkaJavadoc --stacktrace
      - run: docker network prune
      # Store test results
      - store_test_results:
          path: corda-testacles-cordapp-example/build/test-results

      # Store test reports
      #- store_artifacts:
      #    path: corda-testacles-cordapp-example/build/reports
      #    destination: testreport
      # Store generated nodes
      #- store_artifacts:
      #    path: corda-testacles-cordapp-example/build/testacles
      #    destination: testacles

